"""empty message

Revision ID: 15602f953cf4
Revises: 
Create Date: 2021-03-23 21:23:17.314808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15602f953cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('propType', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profiles')
    # ### end Alembic commands ###
